// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTbFFXn3q_f6XQqUgbWqnj1Apzj7uPAWk',
    appId: '1:665416076642:web:87bd3607c27afc8096303b',
    messagingSenderId: '665416076642',
    projectId: 'plus-90',
    authDomain: 'plus-90.firebaseapp.com',
    storageBucket: 'plus-90.firebasestorage.app',
    measurementId: 'G-4GX9C419S1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1p7zQGY3_6GThWlc6U2v8h_lKWee755Q',
    appId: '1:665416076642:ios:776c619e4f0b677596303b',
    messagingSenderId: '665416076642',
    projectId: 'plus-90',
    storageBucket: 'plus-90.firebasestorage.app',
    iosBundleId: 'com.example.plus90Application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1p7zQGY3_6GThWlc6U2v8h_lKWee755Q',
    appId: '1:665416076642:ios:776c619e4f0b677596303b',
    messagingSenderId: '665416076642',
    projectId: 'plus-90',
    storageBucket: 'plus-90.firebasestorage.app',
    iosBundleId: 'com.example.plus90Application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTbFFXn3q_f6XQqUgbWqnj1Apzj7uPAWk',
    appId: '1:665416076642:web:cf31557b2adff2cc96303b',
    messagingSenderId: '665416076642',
    projectId: 'plus-90',
    authDomain: 'plus-90.firebaseapp.com',
    storageBucket: 'plus-90.firebasestorage.app',
    measurementId: 'G-3JPQLW1KDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXgK25l_-F27xF_zmFFcnEE3pJfMNsQM',
    appId: '1:665416076642:android:e96c7e8bd5f35f7096303b',
    messagingSenderId: '665416076642',
    projectId: 'plus-90',
    storageBucket: 'plus-90.firebasestorage.app',
  );

}